# Generated by Django 4.2.7 on 2025-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
