# Generated by Django 4.2.7 on 2025-04-12 19:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("movie", "0002_alter_actor_name_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Genres",
            ),
        ),
    ]
