# Generated by Django 4.2.7 on 2025-04-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_alter_movie_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
        migrations.AddField(
            model_name="movie",
            name="actor_tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
