# Generated by Django 4.2.7 on 2025-04-15 00:38

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("movie", "0005_remove_movie_actors_movie_actor_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actor_tags",
        ),
        migrations.CreateModel(
            name="GenreTaggedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre Tag",
                "verbose_name_plural": "Genre Tags",
            },
        ),
        migrations.CreateModel(
            name="ActorTaggedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor Tag",
                "verbose_name_plural": "Actor Tags",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="actor_tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="movie.ActorTaggedItem",
                to="taggit.Tag",
                verbose_name="Actors",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="movie.GenreTaggedItem",
                to="taggit.Tag",
                verbose_name="Genres",
            ),
        ),
    ]
