# Generated by Django 4.2.7 on 2025-04-15 01:05

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("movie", "0006_remove_movie_actor_tags_genretaggeditem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genretaggeditem",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="actor_tags",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Genres",
            ),
        ),
        migrations.DeleteModel(
            name="ActorTaggedItem",
        ),
        migrations.DeleteModel(
            name="GenreTaggedItem",
        ),
    ]
