# Generated by Django 5.2 on 2025-04-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_remove_genretaggeditem_tag_remove_movie_actor_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
