# Generated by Django 5.2 on 2025-04-16 17:03

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_remove_movie_genres_movie_genres"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Genres",
            ),
        ),
    ]
